name: Build, Analyze, Scan, and Push Docker Images
on:
  push:
    branches:
      - main
jobs:
  build-analyze-scan:
    name: Build, Analyze, Scan, and Push Docker Images  
    runs-on: [Linux]
    steps:
      # Étape 1 : Récupérer le code du repository GitHub
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

